// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class Department
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public int? Capacity { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<TeacherDepartment> TeacherDepartments { get; set; } = new List<TeacherDepartment>();
}