// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class Teacher
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Salary { get; set; }

    public virtual ICollection<TeacherDepartment> TeacherDepartments { get; set; } = new List<TeacherDepartment>();
}