// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class TeacherDepartment
{
    public int TeacherId { get; set; }

    public int DepartmentId { get; set; }

    public int WorkingHours { get; set; }

    public virtual Department Department { get; set; }

    public virtual Teacher Teacher { get; set; }
}