// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolApp.Models;

public partial class Department
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string Name { get; set; }

    public int Capacity { get; set; }

    [Required]
    [StringLength(20)]
    public string Location { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    [InverseProperty("Department")]
    public virtual ICollection<TeacherDepartment> TeacherDepartments { get; set; } = new List<TeacherDepartment>();
}