// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolApp.Models;

[Index("DepartmentId", Name = "IX_Students_DepartmentId")]
public partial class Student
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Age { get; set; }

    public int? DepartmentId { get; set; }

    public string Address { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Students")]
    public virtual Department? Department { get; set; }

    public override string ToString()
    {
        return $"Student Id :{Id} - Student Name : {Name} - Student Department {Department.Name}";
    }
}