// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolApp.Models;

public partial class Teacher
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(60)]
    public string Name { get; set; }

    [Column(TypeName = "money")]
    public decimal Salary { get; set; }

    [InverseProperty("Teacher")]
    public virtual ICollection<TeacherDepartment> TeacherDepartments { get; set; } = new List<TeacherDepartment>();
}