// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolApp.Models;

[PrimaryKey("TeacherId", "DepartmentId")]
[Index("DepartmentId", Name = "IX_TeacherDepartments_DepartmentId")]
public partial class TeacherDepartment
{
    [Key]
    public int TeacherId { get; set; }

    [Key]
    public int DepartmentId { get; set; }

    public int WorkingHours { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("TeacherDepartments")]
    public virtual Department Department { get; set; }

    [ForeignKey("TeacherId")]
    [InverseProperty("TeacherDepartments")]
    public virtual Teacher Teacher { get; set; }
}