// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class Student
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Age { get; set; }

    public string Address { get; set; }

    public int? Did { get; set; }

    public virtual Department DidNavigation { get; set; }

    public override string ToString()
    {
        return $"{Id} - {Name} - {Address}";
    }
}